### ISSUE TITLE
URL to update

### ISSUE THREAD

**Issue by christiore** [nicknochnack/Nopenai#1]
Hi Nicholas thank you for this amazing videos and knowledge. There is a little letter in your cloning url
 git clone https://github.com/nicknochnack/NonOpenAI.  I guess its NopenAI and not NonOpenai :) . Reminds me the challenge you lost for the misspelling.
You rock :)

**Comment by nicknochnack** [comment]
Updated! Thanks a mill man. 

LOL...ah brutal I remember that challenge.
